[package]
name = "otpauth"
version = "0.1.0"
edition = "2021"

[dependencies]
base32 = "0.4.0"
base64 = "0.22.0"
protobuf = "3.4.0"
urlencoding = "2.1.3"

[build-dependencies]
protobuf-codegen = "3.4.0"
